"""initial supervisory schema

Revision ID: 9f3c4a3807c5
Revises: 
Create Date: 2026-09-03 22:05:26.770780
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '9f3c4a3807c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cse_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cse_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('assessment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cse_entities_cse_code'), 'cse_entities', ['cse_code'], unique=True)
    op.create_table('supervisory_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisory_rules_rule_code'), 'supervisory_rules', ['rule_code'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=64), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('expected_monitoring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index('ix_assets_cse_id', 'assets', ['cse_id'], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=64), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('assessment_period', sa.String(length=50), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_batches_batch_code'), 'ingestion_batches', ['batch_code'], unique=True)
    op.create_index('ix_ingestion_batches_cse_id', 'ingestion_batches', ['cse_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_code', sa.String(length=64), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_batch_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('disposition', sa.String(length=250), nullable=True),
    sa.Column('analyst', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_code'), 'alerts', ['alert_code'], unique=True)
    op.create_index('ix_alerts_cse_id', 'alerts', ['cse_id'], unique=False)
    op.create_table('analytics_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_code', sa.String(length=64), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_batch_id', sa.Integer(), nullable=True),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_runs_cse_id', 'analytics_runs', ['cse_id'], unique=False)
    op.create_index(op.f('ix_analytics_runs_run_code'), 'analytics_runs', ['run_code'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_code', sa.String(length=64), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_batch_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('opened_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_analyst', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_code'), 'cases', ['case_code'], unique=True)
    op.create_index('ix_cases_cse_id', 'cases', ['cse_id'], unique=False)
    op.create_table('assessment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_code', sa.String(length=64), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('analytics_run_id', sa.Integer(), nullable=True),
    sa.Column('assessment_period', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analytics_run_id'], ['analytics_runs.id'], ),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessment_reports_cse_id', 'assessment_reports', ['cse_id'], unique=False)
    op.create_index(op.f('ix_assessment_reports_report_code'), 'assessment_reports', ['report_code'], unique=True)
    op.create_table('attention_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('analytics_run_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('attention_level', sa.String(length=30), nullable=False),
    sa.Column('execution_gap_score', sa.Float(), nullable=False),
    sa.Column('negative_space_score', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('peer_deviation_score', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analytics_run_id'], ['analytics_runs.id'], ),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attention_scores_cse_id', 'attention_scores', ['cse_id'], unique=False)
    op.create_table('case_alert_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'alert_id', name='uq_case_alert_link')
    )
    op.create_index(op.f('ix_case_alert_links_alert_id'), 'case_alert_links', ['alert_id'], unique=False)
    op.create_index(op.f('ix_case_alert_links_case_id'), 'case_alert_links', ['case_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escalation_code', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('escalation_level', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('escalated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_alert_id'), 'escalations', ['alert_id'], unique=False)
    op.create_index(op.f('ix_escalations_case_id'), 'escalations', ['case_id'], unique=False)
    op.create_index('ix_escalations_cse_id', 'escalations', ['cse_id'], unique=False)
    op.create_index(op.f('ix_escalations_escalation_code'), 'escalations', ['escalation_code'], unique=True)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_code', sa.String(length=64), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('analytics_run_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score_contribution', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analytics_run_id'], ['analytics_runs.id'], ),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['supervisory_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_cse_id', 'findings', ['cse_id'], unique=False)
    op.create_index(op.f('ix_findings_finding_code'), 'findings', ['finding_code'], unique=True)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_code', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('analyst', sa.String(length=150), nullable=True),
    sa.Column('started_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_case_id'), 'investigations', ['case_id'], unique=False)
    op.create_index('ix_investigations_cse_id', 'investigations', ['cse_id'], unique=False)
    op.create_index(op.f('ix_investigations_investigation_code'), 'investigations', ['investigation_code'], unique=True)
    op.create_table('peer_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('analytics_run_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=150), nullable=False),
    sa.Column('entity_value', sa.Float(), nullable=False),
    sa.Column('peer_average', sa.Float(), nullable=True),
    sa.Column('peer_median', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('assessment_period', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analytics_run_id'], ['analytics_runs.id'], ),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_peer_metrics_cse_id', 'peer_metrics', ['cse_id'], unique=False)
    op.create_table('prioritised_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cse_id', sa.Integer(), nullable=False),
    sa.Column('analytics_run_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analytics_run_id'], ['analytics_runs.id'], ),
    sa.ForeignKeyConstraint(['cse_id'], ['cse_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prioritised_samples_cse_id', 'prioritised_samples', ['cse_id'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_code', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_evidence_evidence_code'), 'finding_evidence', ['evidence_code'], unique=True)
    op.create_index('ix_finding_evidence_finding_id', 'finding_evidence', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finding_evidence_finding_id', table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_evidence_code'), table_name='finding_evidence')
    op.drop_table('finding_evidence')
    op.drop_index('ix_prioritised_samples_cse_id', table_name='prioritised_samples')
    op.drop_table('prioritised_samples')
    op.drop_index('ix_peer_metrics_cse_id', table_name='peer_metrics')
    op.drop_table('peer_metrics')
    op.drop_index(op.f('ix_investigations_investigation_code'), table_name='investigations')
    op.drop_index('ix_investigations_cse_id', table_name='investigations')
    op.drop_index(op.f('ix_investigations_case_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_findings_finding_code'), table_name='findings')
    op.drop_index('ix_findings_cse_id', table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_escalations_escalation_code'), table_name='escalations')
    op.drop_index('ix_escalations_cse_id', table_name='escalations')
    op.drop_index(op.f('ix_escalations_case_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_alert_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_case_alert_links_case_id'), table_name='case_alert_links')
    op.drop_index(op.f('ix_case_alert_links_alert_id'), table_name='case_alert_links')
    op.drop_table('case_alert_links')
    op.drop_index('ix_attention_scores_cse_id', table_name='attention_scores')
    op.drop_table('attention_scores')
    op.drop_index(op.f('ix_assessment_reports_report_code'), table_name='assessment_reports')
    op.drop_index('ix_assessment_reports_cse_id', table_name='assessment_reports')
    op.drop_table('assessment_reports')
    op.drop_index('ix_cases_cse_id', table_name='cases')
    op.drop_index(op.f('ix_cases_case_code'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_analytics_runs_run_code'), table_name='analytics_runs')
    op.drop_index('ix_analytics_runs_cse_id', table_name='analytics_runs')
    op.drop_table('analytics_runs')
    op.drop_index('ix_alerts_cse_id', table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_code'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_ingestion_batches_cse_id', table_name='ingestion_batches')
    op.drop_index(op.f('ix_ingestion_batches_batch_code'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    op.drop_index('ix_assets_cse_id', table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_supervisory_rules_rule_code'), table_name='supervisory_rules')
    op.drop_table('supervisory_rules')
    op.drop_index(op.f('ix_cse_entities_cse_code'), table_name='cse_entities')
    op.drop_table('cse_entities')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
